### PR TITLE
Add an Option to Display Remaining Time before Switching to Next Tab

### PR DESCRIPTION
**Pull request by gdh1995**

### CODE REVIEW

**Comment by gdh1995** [comment]
@akai1831 I've updated this PR, and now the timer tip is only visible if you move mouse into its area (or shake your mouse if it has entered the area). If it's not so useful, you may revert it.

**Comment by akai1831** [comment]
@gdh1995 Thanks for the update! I'm going to check it now.

**Review by akai1831 — APPROVED** [review]

**Comment by akai1831** [comment]
Thanks fro the great adjustment, @gdh1995 . However, we do have set of URLs with different time intervals under Advance Settings and would need to display the countdown or remaining time based on the intervals (seconds) been set per URL. What I have noticed is that the countdown timer was based on the Seconds, this can be found on the top of the Options Page of Revolver - Tabs, it would be great if the countdown timer will be shown in the page based on what have been set on the Advance Settings. I do hope you get my point here. Thanks anyway for having your time to do this. You're such a blessing

**Comment by gdh1995** [comment]
code is reworked and some mentioned bugs are fixed.

**Comment by akai1831** [comment]
Great! It's working as what I've expected. Thanks much @gdh1995 I'm really grateful! ;)

**Comment by akai1831** [comment]
I believe that this would be the last for this, @gdh1995 ;) do we have major fix for the display timer, as it disappear when the page was refreshed or reloaded. Thanks much, once again!!

**Comment by gdh1995** [comment]
@akai1831 These days I'm busy in finishing my study and other work, and I won't have enough rest time until about a month, so I'm sorry but you had better ask others to do further fixing.

**Comment by akai1831** [comment]
Thanks, @gdh1995 . Thanks for the time you've spent on fixing my major issue. Still looking forward on other fixes with other plugin ;)

**Pull request merged**
